#!/bin/bash
set -e
export MPLBACKEND=Agg
source ./venv/bin/activate
ruff format src
ruff format examples
ruff format tests
ruff check --fix src
ruff check --fix examples
ruff check --fix tests
mypy src
pytest tests

echo "Running examples"
cd examples
for f in *.py; do
  python "$f" > /dev/null
done
echo "All good!"
